apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-nlb
  namespace: ingress-nginx
  annotations:
    # Basic NLB setup
    oci.oraclecloud.com/load-balancer-type: "nlb"
    ci.oraclecloud.com/load-balancer-subnet-id: ""
    oci-network-load-balancer.oraclecloud.com/subnet: ""
    oci.oraclecloud.com/security-rule-management-mode: "SL-All"
    oci-network-load-balancer.oraclecloud.com/is-preserve-source: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP